### ISSUE TITLE
Data collection process

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/FictionEro#9]
I'll be updating the collection process here. But do often check on the [data preprocessing document](https://realitybending.github.io/FictionEro/analysis/1_cleaning.html) to see more details.

Regarding prolific, should we create a "[workspace](https://researcher-help.prolific.com/hc/en-gb/articles/4500057146140-Workspaces)" for this project/collab (it seems to be like a shared space with its own funds, collaborators etc) to which we can chip in money and work together? I've never done that but I read and it seems like it's meant for this kind of situation. If you're down, I can give it a shot and create such a workspace and then we see how it works (maybe send me by email your prolific account ids so I can add you as collaborators). 

Although it says:
>you cannot share or transfer funds between different workspaces

I'm assuming that if you already have some funds in your own workspace, you'll need to refund this to you and then re-transfer it to the other workspace, which is slightly annoying.

## 04/02/2024

![image](https://github.com/RealityBending/FictionEro/assets/8875533/589d08d3-ac5e-4542-8d62-bfa5082d8720)

**Comment by MarcoViola88** [comment]
Hi,

> should we create a "[workspace](https://researcher-help.prolific.com/hc/en-gb/articles/4500057146140-Workspaces)" for this project/collab (it seems to be like a shared space with its own funds, collaborators etc) to which we can chip in money and work together?
We currently have no funding for Prolific, we'll see if we can mobilize something.
But in any case, given that we have abundant # of English-speaking participants but not many Italians (at least for now), if we can find some money we probably should prioritize finding them.

***


> do often check on the [data preprocessing document](https://realitybending.github.io/FictionEro/analysis/1_cleaning.html) to see more details.

Of course I'm doing it pretty often, thanks for putting it up, it's very useful :-D
I noticed we are discarding participants from mobile -- can you confirm?

**Comment by DominiqueMakowski** [comment]
> if we can find some money we probably should prioritize finding them

Agreed. I can probably easily find £200 (~45-50 participants)

![image](https://github.com/RealityBending/FictionEro/assets/8875533/c6371d9a-a639-4f70-9a7e-05ce6f78d1c8)

Interestingly for us, there are no prolific participants from Columbia.

> I noticed we are discarding participants from mobile

Currently yes, because doing it on mobile is likely experientially different. So I thought since the data is already quite diverse (in terms of the sources and quality), let's not add more variability there and keep it to the original plan (which was to focus on participants on computers). 

But there is indeed, "unexpectedly" a huge number of mobile participations nonetheless, which can look like a waste of data... So I don't have a strong opinion on what to do about it, you can re-run the cleaning script and comment out the filtering lines, and then run some analyses to see if it changes the results if we keep the mobile users (((earlier when I checked I ***think*** it did make the effects even more significant - but we don't know want to make this decision based on the outcome anyway)))

**Comment by MarcoViola88** [comment]
> But there is indeed, "unexpectedly" a huge number of mobile participations nonetheless, which can look like a waste of data... So I don't have a strong opinion on what to do about it, you can re-run the cleaning script and comment out the filtering lines, and then run some analyses to see if it changes the results if we keep the mobile users (((earlier when I checked I _**think**_ it did make the effects even more significant - but we don't know want to make this decision based on the outcome anyway)))

I suppose that the most honest option would be something like fixing some apriori criteria for filtering outliers -- e.g., completion time >2SD.
And/or, we can fix apriori criteria for excluding/keeping mobile phone users . . . But what do the others think 'bout it???

**Comment by DominiqueMakowski** [comment]
> completion time >2SD

I'm not sure that would be a very good index of low-effort answering (especially since completion times' distribution tend to have a heavy right tail). I would say: assuming we have enough non-mobile data to perform reliable analyses: we go with this as our primary sample. And then we can always re-run the analysis on the mobile users and, best case scenario, show that even in these non-optimal conditions, it still works. I would treat it more as a way to discuss the robustness of our manipulation.

I think it's worth trying to disseminate in facebook groups as well, usually it requires a bit of infiltration but I'm sure there are a lot of groups related to AI art, sex, psychology etc. and many facebook users are computer users

**Comment by DominiqueMakowski** [comment]
> a couple of my posts have been deleted by bots 

Yes this happened to mine a couple of times 🤷 + some reddit communities require a certain amount of "karma" before posting stuff etc. so it's not necessarily the most convenient. And as you say, it's quite popular in the anglo world but maybe not as much in Italy to be worth the trouble (and most italian reddit users would follow english communities anyway). Good luck with facebook!

PS: do not put symbols like `:` or commas or spaces in the URL variables as it complicates the process. Can use underscores

**Comment by DominiqueMakowski** [comment]
We [kinda sorta forgot](https://github.com/RealityBending/FictionEro/issues/2#issuecomment-1904393519) in the excitation. Hence the idea of the [multiverse analysis](https://github.com/RealityBending/FictionEro/discussions/6) to make a strength out of it

We could preregister the non-English arms still (or we could even preregister the whole thing now saying part of the data was collected and we didn't look at it but that would be a lie since I couldn't resist peeking 👀).

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/RealityBending/FictionEro/assets/8875533/809e1d21-3235-459d-980e-95a4ff879df4)

**Comment by MarcoViola88** [comment]
Hi @DominiqueMakowski , am I correct to assume that the link https://realitybending.github.io/FictionEro/analysis/1_cleaning.html does NOT update automatically?
Curious to track the data collection for Italian-speaking people -- asked a hand to many colleagues, but many of them will begin teaching in the next 3-4 weeks, whereas Marco Marini is sharing it on FB.
I'd suggest to see how data collection goes around the end of February before considering Prolific -- what d'ya think?

**Comment by DominiqueMakowski** [comment]
> does NOT update automatically?

Yes, I'll update it tomorrow morning :)

We could *technically* make it to automatically update but it would require some work, so I'll just be updating it every now and then (but if you need me to update it one particular time let me know)

**Comment by MarcoViola88** [comment]
> We could _technically_ make it to automatically update but it would require some work

Naaah, let me be the advocate of ergonomy here: I see no need to get "live update" if that requires any work from you -- better to spare the energy for where they are needed!

... speaking of which, for the sake of making some sketchy plans: do we need to do something else in February beside collecting as many subjects as possible?
Some things that we can (but not necessarily must) do BEFORE analysis might include:
- a bit of literature review (of course we can build on our previous work, but if @marcosperduti has something to share I'd be happy to give a look!)
- requests for the ethical board about an Exp2 involving physiology maybe?

**Comment by guidocor** [comment]
Maybe a silly question, but, do we plan to model the "incremental horniness" of participants?

I noticed that as the experiment advances participants could be turned on progresively. Maybe adding the number of trial as covariate could be interesting!

**Comment by marcosperduti** [comment]
> Maybe adding the number of trial as covariate could be interesting!

I really like the idea...I think that another important parameter, beyond trials order, is the number of "neutral" (non-erotic) or "incongruent" (erotic of the opposite sexual preference) trials that are interposed between the "target" trials (erotic corresponding to the sexual preference).  

> * a bit of literature review (of course we can build on our previous work, but if @marcosperduti has something to share I'd be happy to give a look!)

@MarcoViola88 I can contribute with literature on the effect of AI-authorship on aesthetic appeal.

**Comment by DominiqueMakowski** [comment]
> February beside 

Yes I'd say even we could technically basically start writing an introduction, and bits of the methods. Writing intros is my least favourite bit though, so don't hesitate to have a first crack on it 😁 

> Physio study

Yes, one master student recently joined me and might be interested in helping out with these. I think in a few weeks we can organize a meeting all of us to chat and also start making plans for the future (follow-up studie(s))

**Comment by MarcoViola88** [comment]
I see no major obstracle standing between us and writing the intro. Nor I see reason to rush, but in any case I can try to break the ice -- Dominique, do you propose to create a dedicated file or what? You're the host on GitHub!

However, before beginning to write, maybe we should decide a couple of things:
1. HOW MANY experiments do we want to include in a single study? I was speaking about physiology because maybe a 'thick' article with (EXP1: behavioral data we're collecting online) + (EXP2: physiological data) might be stronger than a mono-experiment. That being said, I'm open-minded, let me know what are your ideas!
2. WHERE do we want to send our paper? Is it too ambitious to give a try to Nature Human Behaviour, and if they reject us scaling back to no less than Computers in Human Behavior?

> @MarcoViola88 I can contribute with literature on the effect of AI-authorship on aesthetic appeal.
That'll be very interesting, thank you! I've browsed that literature and it seems very promising indeed. 
If you have suggested readings relevant for the present work, please share the titles with me, I'd be happy to give a look!

**Comment by guidocor** [comment]
Regarding @MarcoViola88 suggestion of Nature Human Behavior, I think that it could fit as it is an open science multi-national experiment. However, asking a friend who published in it, he suggest to make a good pre-regestriation. NHB value it a lot

**Comment by DominiqueMakowski** [comment]
PS: note that I'm not updating the data on purpose (because the students are on the finishing line writing their dissertation and so I don't want to change their results a few days before completion). However, this is the current sample:

![image](https://github.com/RealityBending/FictionEro/assets/8875533/80fcdedc-c1ac-4305-8a7e-823234627f23)

Italians seem to really like using their phone 😅 

![image](https://github.com/RealityBending/FictionEro/assets/8875533/f328b625-f816-47a3-b2eb-5163b91ae2e8)

**Comment by DominiqueMakowski** [comment]
> I hope we can use data from mobile at least as "robustness check", it'd be so sad to lose it all ...

Yes we'll try to do something with it

> In any case, it looks like it's about time to close data collection, right?

The SONA-recruitment for students ends here next week so we'll close it then and start finalizing the analysis

**Comment by MarcoViola88** [comment]
Great!
I should also be able to start writing a draft introduction (I'm stressing "draft" because I don't wanna be too specific before planning Study2)

**Comment by Antonio8424** [comment]
Hi @DominiqueMakowski , what was the final Colombian sample? Did we found consistent results?

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/RealityBending/FictionEro/assets/8875533/ba85ba7f-ad3a-4326-9635-c31d7247d1e3)


This is the final sample, if we keep Mobile users and focus on hetero, we end up with 657 participants. I haven't rerun the analysis yet. I haven't run the analysis yet but will do soon once I'm done with marking

**Comment by DominiqueMakowski** [comment]
Closing this as well
